Repository wuespace/telestion, pull requests merged in 2024-01, with the labels that each got.

#405 TELESTION-442 Migration with deleted widget type
  frontend-react/src/lib/application/routes/migration/routing.ts
Labels: :bug: bug

#404 TELESTION-454 Writing Backend services in Go
  .github/workflows/backend-go-ci.yml
  backend-go/.nats.conf
  backend-go/Dockerfile
  backend-go/LICENSE
  backend-go/README.md
  backend-go/config.go
  backend-go/docker-compose.ci.yml
  backend-go/docker-compose.yml
  backend-go/example_util_test.go
  backend-go/go.mod
  backend-go/go.sum
  backend-go/lib.go
  backend-go/lib_test.go
  backend-go/nats.go
  backend-go/samples/pub/file.go
  backend-go/samples/pub/main.go
  backend-go/samples/pub/run_multiple_instances.sh
  backend-go/samples/sub/main.go
  backend-go/samples/without_nats/main.go
  backend-go/util.go
Labels: :tulip: enhancement, :hand: help wanted, :books: library

#409 TELESTION-465: Deno samples
  backend-deno/samples/.common.env
  backend-deno/samples/CONTRIBUTING.md
  backend-deno/samples/Dockerfile
  backend-deno/samples/config/README.md
  backend-deno/samples/config/mod.ts
  backend-deno/samples/deno.jsonc
  backend-deno/samples/docker-compose.yml
  backend-deno/samples/latest-value-cache/README.md
  backend-deno/samples/latest-value-cache/mod.ts
  backend-deno/samples/logger/README.md
  backend-deno/samples/logger/mod.ts
  backend-deno/samples/publisher/README.md
  backend-deno/samples/publisher/mod.ts
  backend-deno/samples/requester/README.md
  backend-deno/samples/requester/mod.ts
Labels: :tulip: enhancement

#410 TELESTION-472 Update documentation and remove unused references
  backend-deno/mod.ts
  docs/docs/.pages
  docs/docs/Backend Development/.pages
  docs/docs/Backend Development/index.md
  docs/docs/Backend Development/other-languages.md
  docs/docs/Backend Development/typescript/.pages
  docs/docs/Backend Development/typescript/configuration.md
  docs/docs/Backend Development/typescript/index.md
  docs/docs/Backend Development/typescript/samples.md
  docs/docs/Deployment/concepts.md
  docs/docs/Deployment/docker/index.md
  docs/docs/Deployment/index.md
  docs/docs/Deployment/local/local-nats.md
  docs/docs/Deployment/nats/index.md
  docs/docs/Frontend Development/concepts.md
  docs/docs/_theme_img/favicon.png
  docs/docs/index.md
  docs/docs/message-bus.md
  docs/docs/project-folder-structure.md
  docs/docs/service.md
  docs/mkdocs.yml
Labels: :closed_book: documentation, :tulip: enhancement

#411 TELESTION-443: Error Boundaries
  frontend-react/package.json
  frontend-react/pnpm-lock.yaml
  frontend-react/src/app/index.tsx
  frontend-react/src/app/widgets/error-widget/error-widget.tsx
  frontend-react/src/app/widgets/error-widget/index.tsx
  frontend-react/src/lib/application/index.tsx
  frontend-react/src/lib/widget/component/error-fallback.module.css
  frontend-react/src/lib/widget/component/error-fallback.tsx
  frontend-react/src/lib/widget/component/widget-renderer.tsx
Labels: :tulip: enhancement, :books: library

#412 Disallow widgets to resize based on their content
  frontend-react/src/lib/widget/component/widget-renderer.module.css
Labels: :tulip: enhancement

#415 TELESTION-450: Re-export NATS for convenience
  frontend-react/src/lib/index.ts
  frontend-react/src/lib/nats/index.ts
Labels: :tulip: enhancement

#413 Restore login session upon reload
  frontend-react/src/lib/application/routes/dashboard-editor/routing.ts
  frontend-react/src/lib/application/routes/login/routing.ts
  frontend-react/src/lib/auth/auto-login.ts
  frontend-react/src/lib/auth/controller.ts
  frontend-react/src/lib/auth/index.ts
Labels: :tulip: enhancement

#416 Use submodules instead of exported namespaces in `@wuespace/telestion`
  frontend-react/.eslintrc.cjs
  frontend-react/package.json
  frontend-react/pnpm-lock.yaml
  frontend-react/src/app/index.tsx
  frontend-react/src/lib/application/index.tsx
  frontend-react/src/lib/application/routes/dashboard-editor/routing.ts
  frontend-react/src/lib/application/routes/dashboard-index/routing.ts
  frontend-react/src/lib/application/routes/dashboard-page/routing.ts
  frontend-react/src/lib/application/routes/dashboard.ts
  frontend-react/src/lib/application/routes/login/routing.ts
  frontend-react/src/lib/application/routes/logout.ts
  frontend-react/src/lib/application/routes/migration/routing.ts
  frontend-react/src/lib/application/routes/root.ts
  frontend-react/src/lib/auth/index.ts
  frontend-react/src/lib/index.ts
  frontend-react/src/lib/mod-application.ts
  frontend-react/src/lib/mod-auth.ts
  frontend-react/src/lib/mod-nats.ts
  frontend-react/src/lib/mod-user-data.ts
  frontend-react/src/lib/mod-utils.ts
  frontend-react/src/lib/mod-widget.ts
  frontend-react/src/lib/nats/index.ts
  frontend-react/src/lib/user-data/index.ts
  frontend-react/src/lib/user-data/model.ts
  frontend-react/src/lib/utils.ts
  frontend-react/src/lib/utils/file-utils.ts
  frontend-react/src/lib/utils/index.ts
  frontend-react/src/lib/utils/promise-utils.ts
  frontend-react/src/lib/utils/user-data-utils.ts
  frontend-react/src/lib/widget/index.ts
  frontend-react/tsconfig.json
  frontend-react/typedoc.json
  frontend-react/vite.config.ts
Labels: :closed_book: documentation, :tulip: enhancement

#417 TELESTION-460 Dashboard layout editor
  .github/workflows/frontend-react-ci.yml
  frontend-react/package.json
  frontend-react/pnpm-lock.yaml
  frontend-react/src/app/index.tsx
  frontend-react/src/lib/application/index.scss
  frontend-react/src/lib/application/routes/dashboard-editor/dashboard-editor.module.scss
  frontend-react/src/lib/application/routes/dashboard-editor/dashboard-editor.tsx
  frontend-react/src/lib/application/routes/dashboard-editor/layout-editor/README.md
  frontend-react/src/lib/application/routes/dashboard-editor/layout-editor/components/action-buttons.tsx
  frontend-react/src/lib/application/routes/dashboard-editor/layout-editor/components/cursor.svg
  frontend-react/src/lib/application/routes/dashboard-editor/layout-editor/components/empty-cell.tsx
  frontend-react/src/lib/application/routes/dashboard-editor/layout-editor/components/layout-editor-widget-instance.tsx
  frontend-react/src/lib/application/routes/dashboard-editor/layout-editor/components/layout-editor.module.css
  frontend-react/src/lib/application/routes/dashboard-editor/layout-editor/components/layout-editor.tsx
  frontend-react/src/lib/application/routes/dashboard-editor/layout-editor/components/resize-button.tsx
  frontend-react/src/lib/application/routes/dashboard-editor/layout-editor/components/resize-handle.tsx
  frontend-react/src/lib/application/routes/dashboard-editor/layout-editor/constants.tsx
  frontend-react/src/lib/application/routes/dashboard-editor/layout-editor/hooks/use-layout-editor-keyboard-shortcuts.tsx
  frontend-react/src/lib/application/routes/dashboard-editor/layout-editor/index.ts
  frontend-react/src/lib/application/routes/dashboard-editor/layout-editor/model/layout-editor-model.test.ts
  frontend-react/src/lib/application/routes/dashboard-editor/layout-editor/model/layout-editor-model.ts
  frontend-react/src/lib/application/routes/dashboard-editor/layout-editor/model/layout-editor-props.ts
  frontend-react/src/lib/application/routes/dashboard-editor/routing.ts
  frontend-react/src/lib/application/routes/page-wrapper/page-wrapper.module.css
  frontend-react/src/lib/application/routes/page-wrapper/page-wrapper.tsx
  frontend-react/src/lib/widget/component/widget-renderer.module.css
Labels: :tulip: enhancement

#418 TELESTION-462 Make widgets configurable
  frontend-react/src/app/widgets/error-widget/index.tsx
  frontend-react/src/app/widgets/simple-widget/index.tsx
  frontend-react/src/lib/application/routes/dashboard-editor/dashboard-editor.tsx
  frontend-react/src/lib/application/routes/dashboard-editor/layout-editor/components/resize-button.tsx
  frontend-react/src/lib/application/routes/migration/routing.ts
  frontend-react/src/lib/user-data/index.ts
  frontend-react/src/lib/user-data/json-schema.ts
  frontend-react/src/lib/user-data/model.ts
  frontend-react/src/lib/widget/configuration/configuration-context.tsx
  frontend-react/src/lib/widget/configuration/hooks.tsx
  frontend-react/src/lib/widget/configuration/index.tsx
  frontend-react/src/lib/widget/configuration/model.tsx
  frontend-react/src/lib/widget/index.ts
  frontend-react/src/lib/widget/model.ts
Labels: :tulip: enhancement, :books: library

#419 Deleting dashboards (TELESTION-458) and changing their names (TELESTION-459)
  frontend-react/src/lib/application/routes/dashboard-editor/dashboard-editor.tsx
  frontend-react/src/lib/application/routes/dashboard-editor/routing.ts
Labels: :tulip: enhancement
